### ISSUE TITLE
TypeScript issue

### ISSUE THREAD

**Issue by ivan-kleshnin** [vcfvct/typescript-retry-decorator#33]
Hi there! Seems like a nice and useful library but, unfortunately, I'm getting the following type error:
![Screenshot 2023-07-23 at 12 04 50](https://github.com/vcfvct/typescript-retry-decorator/assets/2128182/d6ad9e23-0c54-4f91-b131-518849b5e928)

I played with different TSconfig & package.json setups, tweaking this and that, but still can't even say if it's a deterministic issue or something specific to my IDE. Sometimes it appears and sometimes – not.
The above screenshot uses `$ tsc --init` > `tsconfig.json` version 🤔 Nothing fancy.

I realize it's hard to help me without a reproduceable code.
My hope is that this error might look familiar to the authors. Otherwise I'll try to find time to come up with a better demo.

**Comment by vcfvct** [comment]
Hi @ivan-kleshnin , I cannot see much of your code and TS configuration etc, but based on the error message, my guess is you may not have the `experimentalDecorators:true` inside your `tsconfig.json`. This is important because TS 5 introduced the ECMAScript decorator which has different signature as the one that Typescript initially implemented.  You can check [the TE5 release note](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators) for more details. 

As for the `tsx` tool, it is interesting and looks promising. Curious, based on your personal usage, what aspects do you think it is better than the `ts-node`?

**Comment by ivan-kleshnin** [comment]
@vcfvct bingo, that helped! 👍 

> As for the tsx tool, it is interesting and looks promising. Curious, based on your personal usage, what aspects do you think it is better than the ts-node?

They have a detailed comparison table here: https://github.com/privatenumber/ts-runtime-comparison

From my experience:
1. It's much faster (like ~10x faster for small one-off scripts 👀 ), 
2. It's a newer and higher level tool with smoother development experience. Does not smap warnings about ESM.
3. Can watch files allowing you to replace `nodemon [folders]` with `tsx --watch [entry]`
